### ISSUE TITLE
Docs issue on NPM page for package import statements?

### ISSUE THREAD

**Issue by roschler** [vpzomtrrfrt/stability-client#24]
The docs on this NPM package page:

https://www.npmjs.com/package/v2-stability-client

Show this:
```js
import { generate } from 'stability-client'
import { generateAsync } from 'stability-client'
```
I had to change them to 'v2-stability-client':
```js
import { generate } from 'v2-stability-client'
import { generateAsync } from 'v2-stability-client'
```

**Comment by vpzomtrrfrt** [comment]
I have nothing to do with that package

**Comment by roschler** [comment]
> I have nothing to do with that package

Sorry.  The name of your package is very close to the one I am using.  I'll repost over there.

**Comment by vpzomtrrfrt** [comment]
`stability-client` is the published package from this repo

**Comment by roschler** [comment]
> `stability-client` is the published package from this repo

Ok, I'll use this one.  Too bad NPM doesn't control what GitHub repos a package is allowed to link to.
