### ISSUE TITLE
result object

### ISSUE THREAD

**Issue by clipartinc** [vpzomtrrfrt/stability-client#3]
When the image gets generated the result object has the name as the full path. Anyone else have this issue?

Can you remove the process.cwd() from the outDir on index.ts#L87?

```
{
root: '', 
dir: '', 
base: 'H:\\blocks\\node\\.out\\dd8ada90-55…4e32-5408-4331-834f-74d3cca0c1ce-0-1088143682.png', 
ext: '.png', 
name: 'H:\\blocks\\node\\.out\\dd8ada90-55…28c64e32-5408-4331-834f-74d3cca0c1ce-0-1088143682'
}
```

**Comment by vpzomtrrfrt** [comment]
that sounds like technically a breaking change, would need to either add an option or wait for a major version bump

**Comment by vpzomtrrfrt** [comment]
also doesn't really seem necessary, so I don't think I'll do anything here
