### ISSUE TITLE
custom distDir not effecting where images are generated

### ISSUE THREAD

**Issue by clipartinc** [vpzomtrrfrt/stability-client#5]
I have a custom distDir set but the default .out is still being used for generated images.

**Comment by vpzomtrrfrt** [comment]
works for me, any other details about when you're seeing this issue?

**Comment by clipartinc** [comment]
I'm using nextJS and the generated images are being saved in the .out directory. In my next.config.js I have a distDir set like this...

module.exports = () => {
    return {
      distDir: 'demo/ai',
  
      webpack: (config) => {
        config.resolve = {
          ...config.resolve,
          fallback: {
            "fs": false,
            "path": false,
            "os": false,
          }
        }
        return config
      },
    }
  }

Is that wrong? Or am I missing something? I'm pretty new at Next.js so it could be my fault. The demo/ai does get created by Next.js, but generateAsync still is placing them into .out/.

**Comment by vpzomtrrfrt** [comment]
you would need to pass the value into the generate call itself, I don't know what you're doing with this config file

**Comment by clipartinc** [comment]
I was able to change the distDir by passing the parameter into the API :)

Can you tell me how to get the result (filePath) which is like...
H:\AIProjects\yourai\public\imagesGenerated\b94b6836-a15f-42df-be08-f24d1a793cfc-0-523944938.png

to a browser friendly URL with forward slashes so  I can display the generated images in a web site.

**Comment by vpzomtrrfrt** [comment]
that depends on your server setup

**Comment by clipartinc** [comment]
I am running on nginx on my own server through Linode. 

I guess I can manipulate the strings at this point. Was hoping there was a built in method for that. Thanks for this repo though! I'm making progress!
