### ISSUE TITLE
Different Height and Width

### ISSUE THREAD

**Issue by abinash23e2** [vpzomtrrfrt/stability-client#8]
Since default is 512 x 512. If I manually add the height: 512 and width: 512, it works. If I put any other numbesr like 250 or 300 into width and height it gives me an error like

**Exception iterating responses: Sizes of tensors must match except in dimension 1. Expected size 32 but got size 31 for tensor number 1 in the list.**

**Comment by vpzomtrrfrt** [comment]
when I try that it gives me "[stability] Unknown: Exception iterating responses: image dimensions must be multiples of 64" so I think that's expected behaviour
