### ISSUE TITLE
InvalidArgument: Must provide image parameters.

### ISSUE THREAD

**Issue by drainmond** [vpzomtrrfrt/stability-client#9]
I'm facing the image parameters error again. The strange thing was it was working initially, and then 30 minutes later it was broken. Tried uninstalling and reinstalling all node packages but it still doesn't work. Am I crazy or did something change in that window of time?

Thanks!

**Comment by vpzomtrrfrt** [comment]
what specifically are you doing that doesn't work?

**Comment by vpzomtrrfrt** [comment]
oh I see it not working either, probably a serverside change

**Comment by drainmond** [comment]
Yes! It appears the interface changed recently in https://github.com/Stability-AI/stability-sdk/blob/main/src/js/generation_pb.d.ts

**Comment by willydavid1** [comment]
how did they solve it?

It was working fine by changing this in the package  `"stability-sdk": "git+https://git@github.com/Stability-AI/api-interfaces.git#1363356",`
 but now it doesn't seem to work and shows the following error

`Error: Must provide image parameters.`

**Comment by vpzomtrrfrt** [comment]
yeah I always suspected that would be a temporary solution, probably need to actually port to the new protobufs now

**Comment by johnsabath** [comment]
Apologies for the breaking change.  Removing these two lines should fix the issue:  https://github.com/vpzomtrrfrt/stability-client/blob/main/src/index.ts#L182-L183

We'll be putting in additional verification checks on our end to prevent this from happening again in the future.

**Comment by willydavid1** [comment]
@johnsabath thank you very much solved the problem!!

**Comment by vpzomtrrfrt** [comment]
Published a 1.6.1 release with that change

**Comment by drainmond** [comment]
I believe @vpzomtrrfrt needs to upload 1.6.1 to NPM in order to solve your problem.

**Comment by vpzomtrrfrt** [comment]
(it's there)

**Comment by drainmond** [comment]
My bad, I was looking at the wrong place. Thanks for the quick fix! 👏🏼

**Comment by bell99431** [comment]
The problem still occured: Must provide image parameters, with 1.6.1 version.
Who knows the sollution?

**Comment by Christopher-Hayes** [comment]
It's working for me. @bell99431 double-check you have the right version or maybe try specifying the width and height if it's not longer optional.

**Comment by iqbalhussainAtSHO** [comment]
@vpzomtrrfrt Please correct me if i'm wrong.

https://www.npmjs.com/package/stability-ts It's says latest version is still 1.3.0
same for this https://yarnpkg.com/?q=stability-ts

I can't seem to upgrade the package version.
